Реорганизация модуля
codex-bot/notify pull request #9
Opened 2017-05-27 09:58 UTC by n0str

2017-05-27 13:42 UTC, neSpecc requested changes

2017-05-27 13:42 UTC, neSpecc commented on notify/main.py
> +        self.sdk = CodexBot('notify', 'notify', 'localhost', 1339, db_config=DB, token=APPLICATION_TOKEN)
1) нужно расхардкодить `app_name` и брать ее из конфига
2) нужно избавиться от передачи `queue_name` и формировать ее внутри sdk. Чтобы разработчик вообще не думал о том, как это работает 
3) все остальные параметры (хост, порт) тоже нужно брать из конфига

2017-05-31 16:32 UTC, neSpecc approved these changes

2017-05-31 16:36 UTC, talyguryn requested changes

2017-05-31 16:36 UTC, talyguryn commented on notify/config.py.sample
> +APPLICATION_NAME = ""
строчку добавь и напиши коммент

2017-05-31 16:36 UTC, talyguryn commented on notify/main.py
> +from config import APPLICATION_TOKEN, APPLICATION_NAME, DB, URL, SERVER
может import *?

2017-05-31 16:44 UTC, talyguryn approved these changes

2017-05-31 16:46 UTC, gohabereg approved these changes

2017-05-31 16:46 UTC, merged